### PR TITLE
GitHub close issue feature

### PR DESCRIPTION
**Pull request by mfrederickson**
Working towards https://github.com/errbit/errbit/issues/371, but I need help writing the test for the close_issue method...

### CODE REVIEW

**Comment by mfrederickson** [comment]
To test this, you'll need the Gemfile entry for errbit_plugin to point to the git repo, the close-issue branch, or point it to your local copy of that branch.

**Comment by mfrederickson** [comment]
@stevecrozz I'm not sure how to make travis's ruby 2.3 test environment happy regarding this:
image
Seen here: https://travis-ci.org/errbit/errbit_github_plugin/jobs/110716111

**Comment by stevecrozz** [comment]
For some reason, it has to be '2.3.0' I'm not sure why its inconsistent, but that's what works in the other repos. Btw. I just released v0.6.0 of errbit_plugin which includes your close_issue updates.

**Comment by stevecrozz** [comment]
@mfrederickson Does that help clear up the build error? Probably we should get this merged and publish a new version before merging the errbit changes.

**Pull request merged**
