### PR TITLE
add basic tests 

### PR DESCRIPTION
**Pull request by tjnet**
#### What's this PR do?

add basic tests to this plugin

#### Where should the reviewer start?

under spec/ directory

#### How should this be manually tested?

```
 $ rspec
```

#### Any background context you want to provide?

Test code allows us to make changes to code quickly. I know it works now because I've run the tests, when I make the changes I need to make, I need to get the tests working again. This saves hours. :smiley_cat: 

#### What are the relevant tickets?

#3 

#### Questions:

- Is this an appropriate testing?
- If I have a mistake, forgive me and tell me how to be a perfect. I will learn it :' :smile:

### CODE REVIEW

**Comment by arthurnn** [comment]
Looking good @tjnet . Will take a more closer look and let you know..
@stevecrozz any thoughts?

**Comment by stevecrozz** [comment]
@arthurnn thanks for the reminder. yes this does look good. the first few tests that just assert the right constants are returned seem a bit silly, but I don't have a better idea and they do at least exercise the right code.

The only change I'd suggest is very minor. I would add: `--require spec_helper` to .rspec and remove the require from the spec file. But I'm good with this either way.

**Comment by tjnet** [comment]
@stevecrozz @arthurnn thanks for your review!
I'll fix it later.

**Comment by tjnet** [comment]
>The only change I'd suggest is very minor. I would add: --require spec_helper to .rspec and remove the require from the spec file. But I'm good with this either way.

I fixed it . Thank you for your review. :smiley_cat:

**Comment by arthurnn** [comment]
merci!

**Comment by tjnet** [comment]
thank you for your feedback and suggestions!

**Pull request merged**
